// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using shared;

#nullable disable

namespace shared.Migrations
{
    [DbContext(typeof(TelemetryDbContext))]
    [Migration("20260221104807_migration5")]
    partial class migration5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("shared.DigitalTwinTelemetryEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("RunId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoomTemperatures")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double>("SunAltitude")
                        .HasColumnType("double precision");

                    b.Property<double>("SunAzimuth")
                        .HasColumnType("double precision");

                    b.Property<double>("SunRadiation")
                        .HasColumnType("double precision");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<double>("WindDirection")
                        .HasColumnType("double precision");

                    b.Property<double>("WindSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id", "RunId", "Timestamp");

                    b.HasIndex("RunId");

                    b.ToTable("DigitalTwinTelemetry", (string)null);
                });

            modelBuilder.Entity("shared.SimulationTelemetryEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("RunId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoomTemperatures")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double>("SunAltitude")
                        .HasColumnType("double precision");

                    b.Property<double>("SunAzimuth")
                        .HasColumnType("double precision");

                    b.Property<double>("SunRadiation")
                        .HasColumnType("double precision");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<double>("WindDirection")
                        .HasColumnType("double precision");

                    b.Property<double>("WindSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id", "RunId", "Timestamp");

                    b.HasIndex("RunId");

                    b.ToTable("SimulationTelemetry", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
