services:
  mongodb:
    image: mongo:latest
    container_name: ddt_mongodb
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ddt_net

  postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: ddt_postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - ddt_net

  postgres-backup:
    image: prodrigestivill/postgres-backup-local
    container_name: ddt_database_backup
    user: postgres:postgres
    volumes:
      - ./docker/backups:/backups
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SCHEDULE=@every 4h00m
      - BACKUP_KEEP_DAYS=2
    networks:
      - ddt_net
    depends_on:
      - postgres

  rabbitmq:
    container_name: ddt_rabbitmq
    image: rabbitmq:4.2.2-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      # TODO: remove management port later
      - "15672:15672"
      - "5672:5672"
      - "15692:15692"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ddt_net

  simulation:
    container_name: ddt_simulation
    build:
      context: ./python
    command: python simulation.py
    environment:
      - RABBITMQ_CONNECTION_STRING=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672/
      - MONGODB_CONNECTION_STRING=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017
    networks:
      - ddt_net
    depends_on:
      - rabbitmq
      - mongodb
    # deploy:
    #   resources:
    #     reservations:
    #       cpus: "0.1"
    #       memory: 128M
    #     limits:
    #       cpus: "2.0"
    #       memory: 256M

  digital-twin:
    container_name: ddt_digital_twin
    build:
      context: ./python
    command: python digital_twin.py
    environment:
      - RABBITMQ_CONNECTION_STRING=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672/
      - MONGODB_CONNECTION_STRING=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017
    networks:
      - ddt_net
    depends_on:
      - rabbitmq
      - mongodb
    # deploy:
    #   resources:
    #     reservations:
    #       cpus: "0.1"
    #       memory: 128M
    #     limits:
    #       cpus: "2.0"
    #       memory: 256M

  api:
    container_name: ddt_api
    build:
      context: csharp
      dockerfile: api/Dockerfile
    environment:
      - ConnectionStrings__TelemetryDbConnection=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - ConnectionStrings__MongoDbConnection=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017
      - ConnectionStrings__RabbitMqConnection=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672/
      - ASPNETCORE_ENVIRONMENT=Production
    # TODO: remove later and use cloudflare tunnel instead
    ports:
      - "6101:8080"
    networks:
      - ddt_net
    depends_on:
      - rabbitmq
      - postgres
      - mongodb

  telemetry_service:
    container_name: ddt_telemetry_service
    build:
      context: csharp
      dockerfile: telemetry_service/Dockerfile
    environment:
      - ConnectionStrings__TelemetryDbConnection=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - ConnectionStrings__RabbitMqConnection=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672/
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - ddt_net
    depends_on:
      - rabbitmq
      - postgres

  website:
    container_name: ddt_website
    build:
      context: csharp
      dockerfile: website/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    # TODO: remove later and use cloudflare tunnel instead
    ports:
      - "6102:80"
    networks:
      - ddt_net
    depends_on:
      - api

  watchtower:
    image: containrrr/watchtower
    container_name: ddt_watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup --label-enable
    environment:
      - DOCKER_API_VERSION=1.45
    networks:
      - ddt_net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: ddt_cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - ddt_net

  prometheus:
    image: prom/prometheus:latest
    container_name: ddt_prometheus
    volumes:
      - ./docker/prometheus/config.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=48h"
    # TODO: remove management port later
    ports:
      - "9090:9090"
    networks:
      - ddt_net
    depends_on:
      - cadvisor

  promtail:
    image: grafana/promtail:latest
    container_name: ddt_promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/promtail/config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - ddt_net

  loki:
    image: grafana/loki:latest
    container_name: ddt_loki
    volumes:
      - ./docker/loki/config.yml:/etc/loki/local-config.yaml
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - ddt_net
    depends_on:
      - promtail

  grafana:
    image: grafana/grafana:latest
    container_name: ddt_grafana
    user: "472"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_SERVER_ROOT_URL=https://district-digital-twin-grafana.260824.xyz
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=${GRAFANA_EMAIL}
      - GF_SMTP_PASSWORD=${GRAFANA_EMAIL_PASSWORD}
      - GF_SMTP_FROM_NAME=Digital Twin Alerts
      - GF_SMTP_FROM_ADDRESS=${GRAFANA_EMAIL}
    networks:
      - ddt_net
    depends_on:
      - prometheus
      - loki

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: ddt_tunnel
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - website
      - grafana
    networks:
      - ddt_net

networks:
  ddt_net:
    driver: bridge

volumes:
  mongodb_data:
  postgres_data:
  portainer_data:
  prometheus_data:
  grafana_data:
  rabbitmq_data:
  loki_data:
